
#web:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#        - "8080:80"
#    volumes:
#        - ./www:/app/www
#        - ./site.conf:/etc/nginx/conf.d/default.conf
#    links:
#        - php

php:
    image: lemp:latest
    container_name: lemp
    ports:
        - "8080:80"
    volumes:
        - ./www:/app/www
        - ./site.conf:/etc/nginx/conf.d/default.conf


mysqldb:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
         MYSQL_DATABASE: doctrine
         MYSQL_ROOT_PASSWORD: root
         MYSQL_USER: dev
         MYSQL_PASSWORD: dev
    ports:
        - "3306:3306"
    volumes:
        - ./data/db/mysql:/var/lib/mysql