web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes: 
        - ./www:/code
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    image: php:7.4-fpm
#    command: ["/usr/local/bin/docker-php-ext-install", "pdo", "pdo_mysql"]
    volumes:
    - ./www:/code

composer:
    image: composer:1.9
    command: ["composer", "install"]
    volumes:
        - ./www:/app
    
mysqldb:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
         MYSQL_DATABASE: doctrine
         MYSQL_ROOT_PASSWORD: root
         MYSQL_USER: dev
         MYSQL_PASSWORD: dev
    ports:
        - "3306:3306"
    volumes:
        - "./data/db/mysql:/var/lib/mysql"